spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - path=/api/v1/users/**

          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - path=/api/v1/hotels/**

          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
              - path=/api/v1/ratings/**

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
    reactor.netty: debug

server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka